language: node_js
node_js:
  - "node"
  - "6"
before_install:
  - sudo pip install awscli
  - ./aws_configure.sh
install:
  - npm install
script:
  - npm run build
  - aws s3 sync build/ s3://${S3_BUCKET}/
