version: 2
jobs:
 build:
    docker:
      - image: node:boron
    steps:
      - checkout
      -  run: |
           npm install
           npm run build
      - save_cache:
           key: build-{{ .Environment.CIRCLE_SHA1 }}
           paths:
             - ./build
 deployment:
   machine: true
   steps:
     - restore_cache:
         key: build-{{ .Environment.CIRCLE_SHA1 }}
     - run aws s3 sync ./build s3://"${STATIC_BUCKET}"/
            
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deployment:
          requires:
            - build
            
