version: 2
jobs:
 build:
    docker:
      - image: node:boron
    steps:
      - checkout
      -  run: |
           npm install
           npm run build
           aws s3 sync ./build s3://"${STATIC_BUCKET}"/
            
